gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_left_finger_fastener_joint
    - gripper_right_finger_fastener_joint
  gains:
    gripper_left_finger_fastener_joint: {p: 40.0, d: 1.0}
    gripper_right_finger_fastener_joint: {p: 40.0, d: 1.0}


